server:
  port: 8081

spring:
  application:
    name: collection-service
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

collection:
  parking-api:
    base-url: https://api.odcloud.kr/api
    api-key: ${PARKING_API_KEY:your-api-key}
  charging-api:
    base-url: https://apis.data.go.kr/B552584/EvCharger
    api-key: "459ff22d488569984e8067fbca79a067f15a0700e53e5fac83cda065638db8ac"
  schedule:
    cron: "0 */5 * * * *"  # 5분마다

kafka:
  topic:
    facility: facility-events
