server:
  port: 8081

spring:
  application:
    name: collection-service
  main:
    banner-mode: console
  data:
    redis:
      host: localhost
      port: 6380
  kafka:
    bootstrap-servers: localhost:9092
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

logging:
  level:
    root: INFO
    com.example.collection: DEBUG
  pattern:
    console: "%d{HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"

collection:
  parking-api:
    api-key: "459ff22d488569984e8067fbca79a067f15a0700e53e5fac83cda065638db8ac"
  charging-api:
    api-key: "459ff22d488569984e8067fbca79a067f15a0700e53e5fac83cda065638db8ac"
  schedule:
    cron: "0 */5 * * * *"

kafka:
  topic:
    facility: facility-events
